Added suggested changes
CSYClubIIITK/CTF-Guide pull request #13
Opened 2024-06-17 17:53 UTC by Aroson1

2024-06-17 18:38 UTC, errorxyz commented
For ref. continuation of https://github.com/CSYClubIIITK/CTF-Guide/pull/4

2024-06-17 18:57 UTC, errorxyz requested changes

2024-06-17 18:57 UTC, errorxyz commented on src/web-exploitation/intro-to-sqli/README.md
>  ## Basis to Tackle SQLi Challenges
```suggestion
## Basics of SQL
```

2024-06-17 18:57 UTC, errorxyz commented on src/web-exploitation/intro-to-sqli/README.md
>  * Look for places from where data might be used to construct a query. Like a textbox, or the url of the website.
```suggestion
* User input from textboxes, URL parameters, etc may be used to construct a SQL query in the backend
```
add this point at the end and it'd be nice to have a small example to improve clarity and explain what happens in the backend at a high level

2024-06-17 18:57 UTC, errorxyz commented on src/web-exploitation/intro-to-sqli/blind-injections.md
> +http://example.com/login
Doesn't make sense to explain a challenge if the user can't access it.
From the user's POV, this section is supposed to be practical and not another reading exercise.

2024-06-18 05:01 UTC, Kanishk-mittal approved these changes

2024-06-26 15:20 UTC, errorxyz commented
continued in #15

2024-06-26 15:20 UTC, closed without merging